### ISSUE TITLE
server.js bug

### ISSUE THREAD

**Issue by cswleocsw** [IEMustDie/Laima#1]
```
var myWebpackConfig = Object.create(webpackConfig);
myWebpackConfig.entry.vendor.push('webpack/hot/dev-server', 'webpack-hot-middleware/client?overlay=false');
myWebpackConfig.plugins.push(new webpack.HotModuleReplacementPlugin(), new webpack.optimize.OccurenceOrderPlugin());

var bundler = webpack(webpackConfig);
```
其中的 myWebpackConfg 並未被後面 webpack 所引用，不過後續行為卻是正常的? 請說明!!!

**Comment by indigofeather** [comment]
```js
var myWebpackConfig = Object.create(webpackConfig);
```

這是 bug，`Object.create` 使得 webpackConfig 內容成為 myWebpackConfig 的 prototype，後續 push 的操作影響的是同一個 prototype，所以這樣跑起來沒噴錯。

參考：https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create

使用 http://www.objectplayground.com/ 的編輯環境示意：
```js
this.webpackConfig = {
    app: ['index.js'],
    vendor: ['g11n']
}

this.myWebpackConfig = Object.create(this.webpackConfig);
this.myWebpackConfig.app.push('dev');
```

產生出來的圖解：
![image](https://cloud.githubusercontent.com/assets/512821/9414610/802fed1c-486c-11e5-8c99-4017e2ad6b13.png)
